version: "1.0"
stages:
  - "clone"
  - "build"
  - "integration"
  - "push"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "nazar-codefresh/test-repo"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "nazar-codefresh/test-repo"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
    build_arguments:
                             			 - TEST_KEY=lolec
